CREATE TABLE TELEFONE(
	ID_TELEFONE			INT				    PRIMARY KEY,
	TELEFONE			  VARCHAR(20)		NOT NULL
);

CREATE TABLE HABILIDADES(
	ID_HABILIDADES		INT				    PRIMARY KEY,
	HABILIDADES			  VARCHAR(300)	NOT NULL
);

CREATE TABLE NINJAS(
	CPF				      INT					    PRIMARY KEY,
	NOME		      	VARCHAR(30)			NOT NULL,
	RUA			      	VARCHAR(60),
	NUM			      	INT,
	NIVER		      	DATE,
	TELEFONE_PK		  INT,
	HABILIDADES_PK	INT,
	FOREIGN KEY(TELEFONE_PK) REFERENCES TELEFONE(ID_TELEFONE),
	FOREIGN KEY(HABILIDADES_PK) REFERENCES HABILIDADES(ID_HABILIDADES)
);
	
CREATE TABLE CLAS(
	IDENT_CLA			INT				    PRIMARY KEY,
	NOME_CLAN			VARCHAR(30)		NOT NULL,
	SIMBOLO				VARCHAR(30),
	HISTORIA			VARCHAR(600),
	LIDER			  	VARCHAR(60)
);

CREATE TABLE NINJAS_CLAS(
    CPF               INT,
    IDENT_CLA         INT,
    FOREIGN KEY (CPF) REFERENCES NINJAS(CPF),
    FOREIGN KEY (IDENT_CLA) REFERENCES CLAS(IDENT_CLA)
);

CREATE TABLE MISSOES(
	N_MISSOES		      	INT			      	PRIMARY KEY,
	NOME_MISSOES		    VARCHAR(30)		  NOT NULL,
	CONDICOES_MISSAO	  VARCHAR(300),
	DESCRICAO			      VARCHAR(600),
	DATA_INICIO		    	DATE
);

CREATE TABLE FAZEM(
	NINJAS_CPF		  	INT,
	MISSOES_N_MISSAO	INT,
	FOREIGN KEY (NINJAS_CPF) REFERENCES NINJAS(CPF),
	FOREIGN KEY (MISSOES_N_MISSAO) REFERENCES MISSOES(N_MISSOES)
);

CREATE TABLE EQUIPAMENTOS(
	IDENT_EQUIP		  	INT		      	PRIMARY KEY,
	DESCRICAO			    VARCHAR(600),
	TIPO			      	VARCHAR(30),
	DISPONIBILIDADE		DATE,
	PROPRIETARIO		  VARCHAR(30)
);

CREATE TABLE TEM(
	MISSOES_N_MISSAO	        INT,
	EQUIPAMENTOS_IDENT_EQUIP	INT,
	FOREIGN KEY (MISSOES_N_MISSAO) REFERENCES MISSOES(N_MISSOES),
	FOREIGN KEY (EQUIPAMENTOS_IDENT_EQUIP) REFERENCES EQUIPAMENTOS(IDENT_EQUIP)
);

CREATE TABLE LOCALIZACAO(
	IDENT_LOCAL		INT		        PRIMARY KEY,
	NOME_LOCAL		VARCHAR(30),
	COORDENADAS		INT,
	REGIAO		  	VARCHAR(30),
	POPULACAO	  	INT
);

CREATE TABLE ESTAO(
	NINJAS_CPF					      INT,
	LOCALIZACAO_IDENT_LOCAL		INT,
	FOREIGN KEY (NINJAS_CPF) REFERENCES NINJAS(CPF),
	FOREIGN KEY (LOCALIZACAO_IDENT_LOCAL) REFERENCES LOCALIZACAO(IDENT_LOCAL)
);

CREATE TABLE ESTAO1(
	IDENT_CLA			          	INT,
	LOCALIZACAO_IDENT_LOCAL		INT,
	FOREIGN KEY (IDENT_CLA) REFERENCES CLAS(IDENT_CLA),
	FOREIGN KEY (LOCALIZACAO_IDENT_LOCAL) REFERENCES LOCALIZACAO(IDENT_LOCAL)
);
